"""edit explanation length task table

Revision ID: 1f98800a4a8a
Revises: 9fcb885fc3e6
Create Date: 2026-09-27 02:30:35.064809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f98800a4a8a'
down_revision: Union[str, Sequence[str], None] = '9fcb885fc3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'explanation',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_comment='説明',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'explanation',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_comment='説明',
               existing_nullable=True)
    # ### end Alembic commands ###
