"""create task table

Revision ID: 9fcb885fc3e6
Revises: c919f7b2a67b
Create Date: 2026-09-25 01:06:30.344006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcb885fc3e6'
down_revision: Union[str, Sequence[str], None] = 'c919f7b2a67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='タイトル'),
    sa.Column('explanation', sa.String(length=100), nullable=True, comment='説明'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='完了状態'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
